# Generated by Django 5.1.7 on 2025-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_debitaccount_default_cashback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitaccount',
            old_name='default_cashback',
            new_name='cashback_rate',
        ),
        migrations.AddField(
            model_name='debitaccount',
            name='accumulated_cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
