# Generated by Django 5.1.7 on 2025-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_default_cashback_debitaccount_cashback_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitaccount',
            name='accumulated_cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
