# Generated by Django 5.1.7 on 2025-03-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_debitaccount_accumulated_cashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitaccount',
            name='cashback_rate',
            field=models.DecimalField(decimal_places=2, default=1.35, help_text='this cashback will be received from some categories of transaction', max_digits=4, verbose_name='default cashback (%)'),
        ),
        migrations.AlterField(
            model_name='debitaccount',
            name='default_commission',
            field=models.DecimalField(decimal_places=2, default=0.35, help_text='base(but not only) commission for each transaction', max_digits=4, verbose_name='default commission (%)'),
        ),
    ]
