# Generated by Django 5.1.7 on 2025-03-26 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_debitaccount_cashback_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitaccount',
            name='default_commission',
            field=models.DecimalField(decimal_places=2, default=0.35, help_text='base(but not only) commission for each transaction', max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='default commission (%)'),
        ),
    ]
