# Generated by Django 5.1.7 on 2025-03-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0006_alter_debitaccount_default_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='debitaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='financeaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
